# docker-compose.yml
services:
  # Next.js Application Service
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - ./data:/app/data:ro
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=/api
    networks:
      - sukien-network
    command: npm run dev
    restart: unless-stopped

  # Production Build Service (optional)
  app-prod:
    build:
      context: .
      dockerfile: ./docker/app-prod/Dockerfile
    volumes:
      - ./data:/app/data:ro
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    networks:
      - sukien-network
    restart: unless-stopped
    profiles:
      - production

  # Nginx Reverse Proxy (optional, for production)
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - sukien-network
    depends_on:
      - app-prod
    profiles:
      - production

networks:
  sukien-network:
    driver: bridge

volumes:
  node_modules:
    driver: local